use std::path::{Path, PathBuf};
use std::time::{Duration, SystemTime};

use iced::keyboard::{self, key::Named, Key, Modifiers};
use iced::widget::{column, container, row, scrollable, stack, text, text_input};
use iced::{time, window, Color, Element, Length, Padding, Size, Subscription, Task, Theme};

mod config;
mod domain;
mod fs_ops;
mod view_modal;
mod view_pane;

use config::{
    dim, ensure_settings_file, expand_tilde, home_dir, load_saved_state, open_in_editor,
    quick_look, row_colors_from, save_state_to_disk, settings_path, Config, SavedState,
};
use domain::{
    add_recent, available_palette_actions, default_zip_filename, filtered_actions, filtered_apps,
    filtered_branches, filtered_recents, filtered_servers, modal_scroll_target, sort_apps,
    sort_containers, sort_entries, sort_processes, Application, AppsState, BackendId, DeleteFocus,
    DockerContainer, DockerSortBy, DockerState, Entry, GitBranch, GitBranchesState, GitInfo,
    Location, NewFilesFocus, PaletteAction, palette_action_enabled, Pane, Process, ProcessSortBy,
    ProcessesState, Prompt, Side, SortBy, SortDir, SshServer, SshServersState,
};
use fs_ops::{
    apps_task, compress_task, copy_task, delete_task, docker_kill_task, docker_ps_task,
    docker_shell, extract_to_temp_task, file_watch_subscription, git_branches_task,
    git_checkout_task, kill_process_task, launch_app, loading_tasks, move_task, open_claude_code,
    pane_watch_subscription, ps_task, ssh_connect, ssh_servers_task, uncompress_task,
};
use view_modal::view_modal;
use view_pane::{name_max_chars, scroll_id, view_pane, viewport_height_estimate};

pub(crate) const PROMPT_ID: &str = "prompt";
/// Shared scroll id for the modal list scrollables. Only one modal is open at
/// a time, so a single id suffices. `modal_scroll_to_selected` snaps it to
/// follow the keyboard cursor in the navigable modals (Go to folder, Apps, Git
/// branches, SSH servers); the mouse-only lists (Docker, Processes) carry the
/// id too but are never snapped.
pub(crate) const MODAL_LIST_ID: &str = "modal-list";
const RECENT_CAP: usize = 50;
/// Enter on a `.zip` over this size pops a confirmation modal before we
/// shell out to `unzip`. 100 MiB.
const LARGE_ARCHIVE_THRESHOLD: u64 = 100 * 1024 * 1024;

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

/// App/window icon, decoded at startup from the PNG generated by
/// `scripts/gen-icon.py`. Embedded so the running binary carries its own
/// icon on Linux/Windows (title bar + taskbar). On macOS the Dock icon for
/// an unbundled `cargo run` is *not* taken from here — that comes from the
/// `.app` bundle built by `scripts/make-macos-app.sh`.
const APP_ICON: &[u8] = include_bytes!("../assets/icon.png");

fn main() -> iced::Result {
    ensure_settings_file();
    let config = Config::load();
    let window_size = config.window_size();
    iced::application("Rho", App::update, App::view)
        .subscription(App::subscription)
        .theme(|_| Theme::Dark)
        .window(window::Settings {
            size: window_size,
            icon: window::icon::from_file_data(APP_ICON, None).ok(),
            ..Default::default()
        })
        .run_with(move || App::new(config))
}

// ---------------------------------------------------------------------------
// Messages
// ---------------------------------------------------------------------------

#[derive(Debug, Clone)]
pub(crate) enum Message {
    ShiftChanged(bool),
    Activate(Side),
    RowClicked(Side, usize),
    GoUpActive,
    MoveSelection(i32, bool),
    PageMove(i32, bool),
    SwitchSide,
    ActivateSelection,
    ToggleSort(Side, SortBy),
    Scrolled(Side, f32, f32),
    /// A selection modal's list scrolled: (scroll_y, viewport_height,
    /// content_height). Lets `modal_scroll_to_selected` track the real
    /// geometry so it only scrolls the cursor into view when off-page.
    ModalScrolled(f32, f32, f32),
    OpenPrompt,
    OpenCopyPrompt,
    OpenMovePrompt,
    OpenDeletePrompt,
    SwitchPromptFocus,
    OpenSettingsFile,
    FilterAppend(String),
    CheckSettings,
    PromptChanged(String),
    PromptSubmit,
    PromptCancel,
    EntriesChunk(Side, u64, Vec<Entry>),
    EntriesDone(Side, u64),
    GitInfoLoaded(Side, u64, Option<GitInfo>),
    EditFile,
    QuickLook,
    CopyFinished(Vec<(Location, Result<(), String>)>),
    MoveFinished(Vec<(Location, Result<(), String>)>),
    DeleteFinished(Vec<(Location, Result<(), String>)>),
    /// `zip` task completed — `Ok(path)` is the new archive's path.
    CompressFinished(Result<PathBuf, String>),
    /// Per-archive extraction results.
    UncompressFinished(Vec<(PathBuf, Result<(), String>)>),
    /// Enter-on-zip extraction completed. On success, navigate the active
    /// pane into `dest` so the user can browse the unpacked contents.
    ExtractedToTemp(PathBuf, Result<(), String>),
    Resized(Size),
    /// The watcher subscription noticed new files in `folder`.
    NewFilesDetected(PathBuf, Vec<String>),
    /// The pane-folder watcher coalesced one-or-more filesystem changes in
    /// `folder` (debounced). Any pane currently showing it reloads in place.
    WatchedDirChanged(PathBuf),
    /// User picked a pane in the NewFiles modal.
    NewFilesPickSide(Side),
    /// Open the command-palette modal (Cmd+Shift+P).
    OpenCommandPalette,
    /// Move the highlight in the current filterable modal (Open / CommandPalette)
    /// by `delta` rows (wraps).
    PromptMove(i32),
    /// User clicked a recent location in the Open modal — open it directly.
    OpenRecent(PathBuf),
    /// User clicked an action in the command palette — activate it directly.
    PaletteSelect(PaletteAction),
    /// `docker ps` completed (or failed) for the Docker modal.
    DockerListLoaded(Result<Vec<DockerContainer>, String>),
    /// User clicked Kill on a container row — start the kill task.
    DockerKill(String),
    /// `docker kill <id>` completed.
    DockerKillFinished(String, Result<(), String>),
    /// User clicked Shell on a container row — spawn a terminal.
    DockerShell(String),
    /// `ps -axo …` completed (or failed) for the Processes modal.
    ProcessesListLoaded(Result<Vec<Process>, String>),
    /// User clicked Kill on a process row — send SIGTERM.
    ProcessKill(u32),
    /// `kill <pid>` completed.
    ProcessKillFinished(u32, Result<(), String>),
    /// User clicked a Docker column header — toggle / switch the sort.
    DockerToggleSort(DockerSortBy),
    /// User clicked a Processes column header — toggle / switch the sort.
    ProcessToggleSort(ProcessSortBy),
    /// `scan_applications` finished (or failed) for the Apps modal.
    AppsListLoaded(Result<Vec<Application>, String>),
    /// User clicked Launch on an app row — `open` the bundle.
    LaunchApp(PathBuf),
    /// `git for-each-ref` completed (or failed) for the GitBranches modal.
    GitBranchesLoaded(Result<Vec<GitBranch>, String>),
    /// User clicked Checkout on a branch row — start the checkout task.
    GitCheckout(String),
    /// `git checkout <branch>` completed.
    GitCheckoutFinished(String, Result<(), String>),
    /// `read_ssh_config` completed (or failed) for the SshServers modal.
    SshServersLoaded(Result<Vec<SshServer>, String>),
    /// User clicked Connect on an SSH server row — spawn a terminal.
    SshConnect(String),
    /// User clicked Open on an SSH server row — point the active pane
    /// at the host's home directory via the remote backend dispatch.
    SshOpenInPane(String),
    /// Global "quit the app" — currently bound to F10.
    ExitApp,
    NoOp,
}

// ---------------------------------------------------------------------------
// App
// ---------------------------------------------------------------------------

struct App {
    config: Config,
    left: Pane,
    right: Pane,
    active: Side,
    prompt: Option<Prompt>,
    shift_held: bool,
    window_size: Size,
    settings_mtime: Option<SystemTime>,
    /// (count, dest) while a copy task is in flight.
    copy_in_progress: Option<(usize, Location)>,
    /// (count, dest) while a move task is in flight.
    move_in_progress: Option<(usize, Location)>,
    /// File count while a delete task is in flight.
    delete_in_progress: Option<usize>,
    /// (count, output_zip) while a compress task is in flight.
    compress_in_progress: Option<(usize, PathBuf)>,
    /// (count, dest_dir) while an uncompress task is in flight.
    uncompress_in_progress: Option<(usize, PathBuf)>,
    /// Source archive path while an Enter-on-zip extraction is running.
    extract_in_progress: Option<PathBuf>,
    /// Error from the most recently finished copy/move/delete/compress/
    /// extract task, shown in red in the status bar until the next such
    /// action starts. `None` once an operation completes cleanly.
    last_error: Option<String>,
    /// New-file detections that arrived while another modal was open. Drained
    /// FIFO when the current modal closes.
    pending_new_files: std::collections::VecDeque<(PathBuf, Vec<String>)>,
    /// Most-recently-visited directories, front-first. Persisted to
    /// `~/.rho-state.yaml`. Updated on every successful navigate.
    recent_locations: Vec<PathBuf>,
    /// Scroll state of the open selection modal's list, so the keyboard
    /// cursor only scrolls the list when it would leave the viewport (see
    /// `modal_scroll_to_selected`). `scroll_y` is the current top offset
    /// (reset to 0 when a list modal opens, maintained by both our own
    /// scroll commands and the user's `ModalScrolled` events); the viewport
    /// height and per-row height come from the scrollable on the first scroll
    /// and fall back to per-modal estimates before then.
    modal_scroll_y: f32,
    modal_viewport_h: Option<f32>,
    modal_row_h: Option<f32>,
}

impl App {
    fn new(config: Config) -> (Self, Task<Message>) {
        let home = home_dir();
        let window_size = config.window_size();
        let settings_mtime = std::fs::metadata(settings_path())
            .and_then(|m| m.modified())
            .ok();

        // Restore last-used folders + active side. Local paths that no
        // longer exist on disk fall back to home; remote locations
        // always restore (we can't cheaply pre-check the host).
        let saved = load_saved_state();
        let restore = |loc: &Location| match loc {
            Location::Local(p) if p.is_dir() => Some(loc.clone()),
            Location::Local(_) => None,
            Location::Remote { .. } => Some(loc.clone()),
        };
        let left_loc = saved
            .as_ref()
            .and_then(|s| restore(&s.left))
            .unwrap_or_else(|| Location::Local(home.clone()));
        let right_loc = saved
            .as_ref()
            .and_then(|s| restore(&s.right))
            .unwrap_or_else(|| Location::Local(home.clone()));
        let active = saved.as_ref().map(|s| s.active).unwrap_or(Side::Left);
        let recent_locations = saved
            .as_ref()
            .map(|s| s.recent.clone())
            .unwrap_or_default();

        let app = Self {
            config,
            left: Pane::empty(left_loc.clone()),
            right: Pane::empty(right_loc.clone()),
            active,
            prompt: None,
            shift_held: false,
            window_size,
            settings_mtime,
            copy_in_progress: None,
            move_in_progress: None,
            delete_in_progress: None,
            compress_in_progress: None,
            uncompress_in_progress: None,
            extract_in_progress: None,
            last_error: None,
            pending_new_files: std::collections::VecDeque::new(),
            recent_locations,
            modal_scroll_y: 0.0,
            modal_viewport_h: None,
            modal_row_h: None,
        };
        // Stat the initial pane paths for the CLAUDE.md / .claude marker so
        // the info bar shows on startup, not just after the first navigate.
        let mut app = app;
        refresh_claude_marker(&mut app.left);
        refresh_claude_marker(&mut app.right);
        // Pane::empty starts at load_generation 0; the initial loads tag
        // their chunks the same way so they're accepted.
        let init = Task::batch([
            loading_tasks(Side::Left, left_loc, 0),
            loading_tasks(Side::Right, right_loc, 0),
        ]);
        (app, init)
    }

    fn save_state(&self) {
        save_state_to_disk(&SavedState {
            left: self.left.location.clone(),
            right: self.right.location.clone(),
            active: self.active,
            recent: self.recent_locations.clone(),
        });
    }

    fn pane(&self, side: Side) -> &Pane {
        match side {
            Side::Left => &self.left,
            Side::Right => &self.right,
        }
    }

    /// True iff the active pane is inside a git repository (i.e. `git_info`
    /// was populated by the per-navigate probe). Used by the command palette
    /// to gate the Git: branch action.
    fn in_git_repo(&self) -> bool {
        self.pane(self.active).git_info.is_some()
    }

    /// True iff both panes point at local paths. Cross-pane ops (copy,
    /// move, compress, uncompress) need this in Phase 2 because their
    /// implementations only know how to talk to the local filesystem.
    fn both_panes_local(&self) -> bool {
        self.left.location.is_local() && self.right.location.is_local()
    }

    fn pane_mut(&mut self, side: Side) -> &mut Pane {
        match side {
            Side::Left => &mut self.left,
            Side::Right => &mut self.right,
        }
    }

    fn navigate(&mut self, side: Side, location: Location) -> Task<Message> {
        let generation = self.pane_mut(side).navigate(location.clone());
        refresh_claude_marker(self.pane_mut(side));
        // The "Go to folder" recents list stays PathBuf-shaped, so
        // only local navigations feed it. Remote panes are reachable
        // via the SSH-server picker instead.
        if let Location::Local(p) = &location {
            add_recent(&mut self.recent_locations, p.clone(), RECENT_CAP);
        }
        self.save_state();
        Task::batch([
            loading_tasks(side, location, generation),
            self.ensure_active_visible(),
        ])
    }

    fn page_size(&self) -> i32 {
        let vh = self
            .pane(self.active)
            .viewport_height
            .unwrap_or_else(|| viewport_height_estimate(self.window_size.height));
        let rows = (vh / self.config.row_height_px).floor() as i32 - 1;
        rows.max(1)
    }

    fn ensure_active_visible(&mut self) -> Task<Message> {
        let side = self.active;
        let fallback_vh = viewport_height_estimate(self.window_size.height);
        let stride = self.config.row_height_px;
        let pane = self.pane_mut(side);
        let vh = pane.viewport_height.unwrap_or(fallback_vh);
        let row_top = pane.selected as f32 * stride;
        let row_bottom = row_top + stride;
        let view_top = pane.scroll_y;
        let view_bottom = view_top + vh;

        let target = if row_top < view_top {
            Some(row_top)
        } else if row_bottom > view_bottom {
            Some((row_bottom - vh).max(0.0))
        } else {
            None
        };

        if let Some(y) = target {
            pane.scroll_y = y;
            scrollable::scroll_to(scroll_id(side), scrollable::AbsoluteOffset { x: 0.0, y })
        } else {
            Task::none()
        }
    }

    /// Force-scroll `side`'s pane so its selected row sits roughly a third of
    /// the way down the viewport. Used right after a `pending_focus` request
    /// is resolved — `ensure_active_visible` is too conservative there because
    /// `pane.scroll_y` may be stale from before the navigation.
    fn scroll_to_focused(&mut self, side: Side) -> Task<Message> {
        let fallback_vh = viewport_height_estimate(self.window_size.height);
        let stride = self.config.row_height_px;
        let pane = self.pane_mut(side);
        let vh = pane.viewport_height.unwrap_or(fallback_vh);
        let row_top = pane.selected as f32 * stride;
        // Leave some context above the file so it's not glued to the top edge.
        let y = (row_top - vh / 3.0).max(0.0);
        pane.scroll_y = y;
        scrollable::scroll_to(scroll_id(side), scrollable::AbsoluteOffset { x: 0.0, y })
    }

    /// `(selected, row_count)` for the open selection modal whose list is
    /// keyboard-navigable and shares `MODAL_LIST_ID` (Go to folder / Apps /
    /// Git branches / SSH servers). `None` for everything else — modals with
    /// no cursor or no scrollable list (Command Palette, Docker, Processes).
    fn current_modal_selection(&self) -> Option<(usize, usize)> {
        match self.prompt.as_ref() {
            Some(Prompt::Open {
                input,
                recents,
                selected,
            }) => {
                let n = filtered_recents(recents, input).len();
                (n > 0).then_some((*selected, n))
            }
            Some(Prompt::Apps {
                state: AppsState::Loaded(list),
                input,
                selected,
            }) => {
                let n = filtered_apps(list, input).len();
                (n > 0).then_some((*selected, n))
            }
            Some(Prompt::GitBranches {
                state: GitBranchesState::Loaded(list),
                input,
                selected,
                ..
            }) => {
                let n = filtered_branches(list, input).len();
                (n > 0).then_some((*selected, n))
            }
            Some(Prompt::SshServers {
                state: SshServersState::Loaded(list),
                input,
                selected,
            }) => {
                let n = filtered_servers(list, input).len();
                (n > 0).then_some((*selected, n))
            }
            _ => None,
        }
    }

    /// (viewport_height, row_height) estimates used before the modal list has
    /// reported real geometry via `ModalScrolled`. The Go-to-folder list is
    /// 240px tall with slightly taller rows; the rest are 360px. Once a scroll
    /// happens the tracked values take over and these stop mattering.
    fn modal_fallback_geometry(&self) -> (f32, f32) {
        match self.prompt.as_ref() {
            Some(Prompt::Open { .. }) => (240.0, 26.0),
            _ => (360.0, 23.0),
        }
    }

    /// Reset the tracked modal scroll state. Called when a list modal opens so
    /// the fresh scrollable (which starts at the top) isn't judged against a
    /// previous modal's offset/geometry.
    fn reset_modal_scroll(&mut self) {
        self.modal_scroll_y = 0.0;
        self.modal_viewport_h = None;
        self.modal_row_h = None;
    }

    /// Scroll the open selection modal's list so the highlighted row stays in
    /// view — but only when it would otherwise leave the viewport, so the list
    /// doesn't drift on every arrow press (`modal_scroll_target`). Mirrors the
    /// panes' `ensure_active_visible`, using the scroll offset / viewport /
    /// row height tracked from `ModalScrolled` (falling back to per-modal
    /// estimates before the first scroll).
    fn modal_scroll_to_selected(&mut self) -> Task<Message> {
        let Some((selected, _n)) = self.current_modal_selection() else {
            return Task::none();
        };
        let (fallback_vh, fallback_row_h) = self.modal_fallback_geometry();
        let vh = self.modal_viewport_h.unwrap_or(fallback_vh);
        let row_h = self.modal_row_h.unwrap_or(fallback_row_h);
        match modal_scroll_target(selected, row_h, vh, self.modal_scroll_y) {
            Some(y) => {
                self.modal_scroll_y = y;
                scrollable::scroll_to(
                    scrollable::Id::new(MODAL_LIST_ID),
                    scrollable::AbsoluteOffset { x: 0.0, y },
                )
            }
            None => Task::none(),
        }
    }

    fn reload_both_panes(&mut self) -> Task<Message> {
        let left_loc = self.left.location.clone();
        let right_loc = self.right.location.clone();
        let left_gen = self.left.navigate(left_loc.clone());
        let right_gen = self.right.navigate(right_loc.clone());
        refresh_claude_marker(&mut self.left);
        refresh_claude_marker(&mut self.right);
        Task::batch([
            loading_tasks(Side::Left, left_loc, left_gen),
            loading_tasks(Side::Right, right_loc, right_gen),
        ])
    }

    /// Reload, in place, any pane currently showing the local directory
    /// `path` (both, if they show the same folder). Driven by the debounced
    /// folder watcher. `Pane::reload` keeps the filter/sort/scroll and
    /// re-homes the cursor, and routes through the same generation-tagged
    /// streaming load as a navigate, so a refresh mid-load can't leak stale
    /// rows. Remote panes aren't watched, so they never match here.
    fn refresh_local_dir(&mut self, path: &Path) -> Task<Message> {
        let mut tasks = Vec::new();
        for side in [Side::Left, Side::Right] {
            let loc = self.pane(side).location.clone();
            if matches!(&loc, Location::Local(p) if p == path) {
                let generation = self.pane_mut(side).reload();
                refresh_claude_marker(self.pane_mut(side));
                tasks.push(loading_tasks(side, loc, generation));
            }
        }
        Task::batch(tasks)
    }

    fn update(&mut self, msg: Message) -> Task<Message> {
        // Modals without a text_input let navigation keys fall through to
        // top-level messages. Rewrite them to focus-aware actions so the user
        // can drive the dialog with the keyboard alone: Enter activates the
        // focused button, Tab/←/→ flip focus.
        let msg = match (&self.prompt, msg) {
            (Some(Prompt::Delete { focus, .. }), m) => {
                let focus = *focus;
                match m {
                    Message::ActivateSelection => match focus {
                        DeleteFocus::Confirm => Message::PromptSubmit,
                        DeleteFocus::Cancel => Message::PromptCancel,
                    },
                    Message::SwitchSide => Message::SwitchPromptFocus,
                    other => other,
                }
            }
            // Same Cancel/Confirm keyboard wiring as Delete — Enter routes to
            // the focused button, Tab/←/→ flip focus.
            (Some(Prompt::ConfirmLargeExtract { focus, .. }), m) => {
                let focus = *focus;
                match m {
                    Message::ActivateSelection => match focus {
                        DeleteFocus::Confirm => Message::PromptSubmit,
                        DeleteFocus::Cancel => Message::PromptCancel,
                    },
                    Message::SwitchSide => Message::SwitchPromptFocus,
                    other => other,
                }
            }
            (Some(Prompt::NewFiles { focus, .. }), m) => {
                let focus = *focus;
                match m {
                    Message::ActivateSelection => match focus {
                        NewFilesFocus::No => Message::PromptCancel,
                        NewFilesFocus::Left => Message::NewFilesPickSide(Side::Left),
                        NewFilesFocus::Right => Message::NewFilesPickSide(Side::Right),
                    },
                    Message::SwitchSide => Message::SwitchPromptFocus,
                    other => other,
                }
            }
            // Open, CommandPalette, and Apps all have a text_input on top
            // and a filterable list below. text_input consumes Enter / Left
            // / Right / Backspace / printable chars, so ↑/↓/PgUp/PgDn/Tab
            // fall through here and we redirect them to PromptMove for list
            // navigation. Enter is delivered via text_input's on_submit →
            // PromptSubmit and doesn't reach this redirect.
            (
                Some(Prompt::Open { .. })
                | Some(Prompt::CommandPalette { .. })
                | Some(Prompt::Apps { .. })
                | Some(Prompt::GitBranches { .. })
                | Some(Prompt::SshServers { .. }),
                m,
            ) => match m {
                Message::MoveSelection(delta, _) => Message::PromptMove(delta),
                Message::PageMove(dir, _) => Message::PromptMove(dir * 5),
                Message::SwitchSide => Message::PromptMove(1),
                other => other,
            },
            (_, m) => m,
        };

        // While *any* modal is open, suppress pane-nav keys that text_input
        // didn't capture (Tab, F-keys, arrows-in-no-input).
        if self.prompt.is_some() {
            match &msg {
                Message::MoveSelection(..)
                | Message::PageMove(..)
                | Message::ActivateSelection
                | Message::SwitchSide
                | Message::GoUpActive
                | Message::EditFile
                | Message::QuickLook
                | Message::OpenCopyPrompt
                | Message::OpenMovePrompt
                | Message::OpenDeletePrompt
                | Message::OpenCommandPalette
                | Message::FilterAppend(..) => return Task::none(),
                _ => {}
            }
        }

        match msg {
            Message::ShiftChanged(state) => {
                self.shift_held = state;
            }
            Message::Activate(side) => {
                if self.active != side {
                    self.active = side;
                    self.save_state();
                }
            }
            Message::RowClicked(side, row_index) => {
                let active_changed = self.active != side;
                self.active = side;
                let extend = self.shift_held;
                self.pane_mut(side).move_to(row_index as i32, extend);
                if active_changed {
                    self.save_state();
                }
                return self.ensure_active_visible();
            }
            Message::GoUpActive => {
                let side = self.active;
                // If a filter is active, Backspace edits the filter instead
                // of leaving the current directory.
                let filter_shrank = {
                    let pane = self.pane_mut(side);
                    if !pane.filter.is_empty() {
                        let prior = pane.cursor_name();
                        pane.filter.pop();
                        pane.recompute_visible(prior.as_deref());
                        true
                    } else {
                        false
                    }
                };
                if filter_shrank {
                    // visible row count changed — re-anchor scroll so the
                    // newly-matching rows are visible. See FilterAppend.
                    return self.ensure_active_visible();
                }
                if let Some(parent) = self.pane(side).location.parent() {
                    return self.navigate(side, parent);
                }
            }
            Message::MoveSelection(delta, extend) => {
                let side = self.active;
                self.pane_mut(side).move_by(delta, extend);
                return self.ensure_active_visible();
            }
            Message::PageMove(dir, extend) => {
                let page = self.page_size();
                let side = self.active;
                self.pane_mut(side).move_by(dir * page, extend);
                return self.ensure_active_visible();
            }
            Message::SwitchSide => {
                self.active = self.active.other();
                self.save_state();
                return self.ensure_active_visible();
            }
            Message::ActivateSelection => {
                let side = self.active;
                if self.pane(side).selected == 0 {
                    if let Some(parent) = self.pane(side).location.parent() {
                        return self.navigate(side, parent);
                    }
                    return Task::none();
                }
                let pane = self.pane(side);
                if let Some(entry) = pane.entry_at(pane.selected) {
                    if entry.is_dir {
                        return self.navigate(side, pane.location.join(&entry.name));
                    }
                    // Files: every action below (zip extract, open in
                    // default app) is local-only. Phase 2 lists remote
                    // panes but can't yet pull a remote file down to
                    // open it — bail quietly.
                    if !pane.location.is_local() {
                        return Task::none();
                    }
                    let path = pane.path().join(&entry.name);
                    if is_zip(&path) {
                        let size = entry.size.unwrap_or(0);
                        if size > LARGE_ARCHIVE_THRESHOLD {
                            self.prompt = Some(Prompt::ConfirmLargeExtract {
                                archive_path: path,
                                size_bytes: size,
                                focus: DeleteFocus::Cancel,
                            });
                            return Task::none();
                        }
                        self.last_error = None;
                        self.extract_in_progress = Some(path.clone());
                        return extract_to_temp_task(path);
                    }
                    if let Err(e) = open::that_detached(&path) {
                        eprintln!("failed to open {}: {}", path.display(), e);
                    }
                }
            }
            Message::ToggleSort(side, by) => {
                self.active = side;
                self.pane_mut(side).toggle_sort(by);
                return self.ensure_active_visible();
            }
            Message::Scrolled(side, scroll_y, vh) => {
                let pane = self.pane_mut(side);
                pane.scroll_y = scroll_y;
                pane.viewport_height = Some(vh);
            }
            Message::ModalScrolled(scroll_y, vh, content_h) => {
                self.modal_scroll_y = scroll_y;
                self.modal_viewport_h = Some(vh);
                // Uniform rows: content_height / row_count is the row height.
                // Capture it against the current count so a later filter that
                // changes the count doesn't skew the stored height.
                if let Some((_, n)) = self.current_modal_selection() {
                    if n > 0 {
                        self.modal_row_h = Some(content_h / n as f32);
                    }
                }
            }
            Message::OpenPrompt => {
                self.reset_modal_scroll();
                self.prompt = Some(Prompt::Open {
                    input: String::new(),
                    recents: self.recent_locations.clone(),
                    selected: 0,
                });
                return text_input::focus(text_input::Id::new(PROMPT_ID));
            }
            Message::OpenCopyPrompt => {
                let other = self.active.other();
                let dest = self.pane(other).location.to_string();
                self.prompt = Some(Prompt::Copy { input: dest });
                return text_input::focus(text_input::Id::new(PROMPT_ID));
            }
            Message::OpenMovePrompt => {
                let other = self.active.other();
                let dest = self.pane(other).location.to_string();
                self.prompt = Some(Prompt::Move { input: dest });
                return text_input::focus(text_input::Id::new(PROMPT_ID));
            }
            Message::OpenDeletePrompt => {
                let paths = self.pane(self.active).marked_locations();
                if !paths.is_empty() {
                    // Default focus on Cancel: a stray Enter shouldn't delete.
                    self.prompt = Some(Prompt::Delete {
                        paths,
                        focus: DeleteFocus::Cancel,
                    });
                }
            }
            Message::SwitchPromptFocus => match self.prompt.as_mut() {
                Some(Prompt::Delete { focus, .. })
                | Some(Prompt::ConfirmLargeExtract { focus, .. }) => *focus = focus.toggle(),
                Some(Prompt::NewFiles { focus, .. }) => *focus = focus.next(),
                _ => {}
            },
            Message::OpenSettingsFile => {
                ensure_settings_file();
                let path = settings_path();
                if let Err(e) = open::that_detached(&path) {
                    eprintln!("failed to open {}: {}", path.display(), e);
                }
            }
            Message::CheckSettings => {
                let current = std::fs::metadata(settings_path())
                    .and_then(|m| m.modified())
                    .ok();
                if current != self.settings_mtime {
                    self.settings_mtime = current;
                    self.config = Config::load();
                }
            }
            Message::PromptChanged(value) => {
                if let Some(prompt) = self.prompt.as_mut() {
                    match prompt {
                        Prompt::Open {
                            input,
                            recents,
                            selected,
                        } => {
                            *input = value;
                            // The filtered view just shrank or grew — clamp
                            // the highlight so it points at a real row.
                            let n = filtered_recents(recents, input).len();
                            *selected = if n == 0 { 0 } else { (*selected).min(n - 1) };
                        }
                        Prompt::Copy { input }
                        | Prompt::Move { input }
                        | Prompt::Compress { input }
                        | Prompt::Uncompress { input } => {
                            *input = value;
                        }
                        Prompt::CommandPalette {
                            input,
                            selected,
                            actions,
                            ..
                        } => {
                            *input = value;
                            let n = filtered_actions(actions, input).len();
                            *selected = if n == 0 { 0 } else { (*selected).min(n - 1) };
                        }
                        Prompt::Docker { input, .. } | Prompt::Processes { input, .. } => {
                            *input = value;
                        }
                        Prompt::Apps {
                            input,
                            state,
                            selected,
                        } => {
                            *input = value;
                            if let AppsState::Loaded(list) = state {
                                let n = filtered_apps(list, input).len();
                                *selected = if n == 0 { 0 } else { (*selected).min(n - 1) };
                            }
                        }
                        Prompt::GitBranches {
                            input,
                            state,
                            selected,
                            ..
                        } => {
                            *input = value;
                            if let GitBranchesState::Loaded(list) = state {
                                let n = filtered_branches(list, input).len();
                                *selected = if n == 0 { 0 } else { (*selected).min(n - 1) };
                            }
                        }
                        Prompt::SshServers {
                            input,
                            state,
                            selected,
                        } => {
                            *input = value;
                            if let SshServersState::Loaded(list) = state {
                                let n = filtered_servers(list, input).len();
                                *selected = if n == 0 { 0 } else { (*selected).min(n - 1) };
                            }
                        }
                        Prompt::Delete { .. }
                        | Prompt::ConfirmLargeExtract { .. }
                        | Prompt::NewFiles { .. }
                        | Prompt::KeyboardShortcuts => {}
                    }
                    // Filtering shifts which row the (clamped) cursor points at,
                    // so re-follow it — e.g. typing to a single match should
                    // bring that row into view.
                    return self.modal_scroll_to_selected();
                }
            }
            Message::PromptSubmit => {
                // A fresh submit (copy/move/delete/compress/extract) clears
                // any error left over from the previous one.
                self.last_error = None;
                let task = if let Some(prompt) = self.prompt.take() {
                    match prompt {
                        Prompt::Open {
                            input,
                            recents,
                            selected,
                        } => {
                            // Priority: typed input first (if it resolves to
                            // a real directory), otherwise the highlighted
                            // recent. This lets the user type a fresh path
                            // even when a substring matches an existing one.
                            let typed = PathBuf::from(expand_tilde(input.trim()));
                            let target = if typed.is_dir() {
                                Some(typed)
                            } else {
                                let filtered = filtered_recents(&recents, &input);
                                filtered.get(selected).map(|&p| p.clone())
                            };
                            target
                                .filter(|p| p.is_dir())
                                .map(|p| self.navigate(self.active, Location::Local(p)))
                        }
                        Prompt::Copy { input } => {
                            let dest = parse_dest_location(&input);
                            if dest_exists(&dest) {
                                let srcs = self.pane(self.active).marked_locations();
                                if !srcs.is_empty() {
                                    self.copy_in_progress = Some((srcs.len(), dest.clone()));
                                    Some(copy_task(srcs, dest))
                                } else {
                                    None
                                }
                            } else {
                                None
                            }
                        }
                        Prompt::Move { input } => {
                            let dest = parse_dest_location(&input);
                            if dest_exists(&dest) {
                                let srcs = self.pane(self.active).marked_locations();
                                if !srcs.is_empty() {
                                    self.move_in_progress = Some((srcs.len(), dest.clone()));
                                    Some(move_task(srcs, dest))
                                } else {
                                    None
                                }
                            } else {
                                None
                            }
                        }
                        Prompt::Compress { input } => {
                            let output = PathBuf::from(expand_tilde(input.trim()));
                            let srcs = self.pane(self.active).marked_paths();
                            let working_dir = self.pane(self.active).path().to_path_buf();
                            if !srcs.is_empty() {
                                self.compress_in_progress = Some((srcs.len(), output.clone()));
                                Some(compress_task(srcs, output, working_dir))
                            } else {
                                None
                            }
                        }
                        Prompt::Uncompress { input } => {
                            let dest = PathBuf::from(expand_tilde(input.trim()));
                            if dest.is_dir() {
                                let archives = self.pane(self.active).marked_paths();
                                if !archives.is_empty() {
                                    self.uncompress_in_progress =
                                        Some((archives.len(), dest.clone()));
                                    Some(uncompress_task(archives, dest))
                                } else {
                                    None
                                }
                            } else {
                                None
                            }
                        }
                        Prompt::Delete { paths, .. } => {
                            if !paths.is_empty() {
                                self.delete_in_progress = Some(paths.len());
                                Some(delete_task(paths))
                            } else {
                                None
                            }
                        }
                        Prompt::ConfirmLargeExtract { archive_path, .. } => {
                            self.extract_in_progress = Some(archive_path.clone());
                            Some(extract_to_temp_task(archive_path))
                        }
                        // NewFiles uses NewFilesPickSide / PromptCancel, never
                        // PromptSubmit. If we somehow get here, just drop it.
                        Prompt::NewFiles { .. } => None,
                        Prompt::CommandPalette {
                            input,
                            selected,
                            actions,
                            dropbox_configured,
                        } => {
                            let filtered = filtered_actions(&actions, &input);
                            match filtered.get(selected).copied() {
                                Some(action)
                                    if palette_action_enabled(action, dropbox_configured) =>
                                {
                                    return self.execute_palette_action(action);
                                }
                                // Highlighted row is disabled (e.g. Open
                                // Dropbox without credentials): keep the modal
                                // open so Enter feels inert rather than
                                // dismissing it.
                                Some(_) => {
                                    self.prompt = Some(Prompt::CommandPalette {
                                        input,
                                        selected,
                                        actions,
                                        dropbox_configured,
                                    });
                                    None
                                }
                                None => None,
                            }
                        }
                        // Docker / Processes have a filter input but actions
                        // are mouse-only — Enter is a no-op. Re-instate the
                        // prompt so the modal doesn't close.
                        Prompt::Docker {
                            state,
                            input,
                            sort_by,
                            sort_dir,
                        } => {
                            self.prompt = Some(Prompt::Docker {
                                state,
                                input,
                                sort_by,
                                sort_dir,
                            });
                            None
                        }
                        Prompt::Processes {
                            state,
                            input,
                            sort_by,
                            sort_dir,
                        } => {
                            self.prompt = Some(Prompt::Processes {
                                state,
                                input,
                                sort_by,
                                sort_dir,
                            });
                            None
                        }
                        // Apps modal: Enter launches the highlighted row.
                        // If no row is selectable (empty / loading / error),
                        // fall through to closing the modal silently.
                        Prompt::Apps {
                            state,
                            input,
                            selected,
                        } => {
                            let target = if let AppsState::Loaded(list) = &state {
                                let filtered = filtered_apps(list, &input);
                                filtered.get(selected).map(|&a| a.path.clone())
                            } else {
                                None
                            };
                            if let Some(path) = target {
                                if let Err(e) = launch_app(&path) {
                                    eprintln!("launch {} failed: {}", path.display(), e);
                                }
                                None
                            } else {
                                // Nothing to launch — keep the modal open.
                                self.prompt = Some(Prompt::Apps {
                                    state,
                                    input,
                                    selected,
                                });
                                None
                            }
                        }
                        // GitBranches modal: Enter checks out the highlighted
                        // branch. Empty/loading/error keeps the modal open.
                        Prompt::GitBranches {
                            state,
                            input,
                            selected,
                            repo_path,
                        } => {
                            let branch_name = if let GitBranchesState::Loaded(list) = &state {
                                let filtered = filtered_branches(list, &input);
                                filtered.get(selected).map(|&b| b.name.clone())
                            } else {
                                None
                            };
                            if let Some(branch) = branch_name {
                                Some(git_checkout_task(repo_path.clone(), branch))
                            } else {
                                self.prompt = Some(Prompt::GitBranches {
                                    state,
                                    input,
                                    selected,
                                    repo_path,
                                });
                                None
                            }
                        }
                        // Informational modal — Enter is a no-op; put the
                        // prompt back so the modal doesn't close.
                        Prompt::KeyboardShortcuts => {
                            self.prompt = Some(Prompt::KeyboardShortcuts);
                            None
                        }
                        // SshServers: Enter connects to the highlighted row.
                        // Empty/loading/error keeps the modal open.
                        Prompt::SshServers {
                            state,
                            input,
                            selected,
                        } => {
                            let alias = if let SshServersState::Loaded(list) = &state {
                                let filtered = filtered_servers(list, &input);
                                filtered.get(selected).map(|&s| s.alias.clone())
                            } else {
                                None
                            };
                            if let Some(alias) = alias {
                                if let Err(e) =
                                    ssh_connect(&alias, self.config.terminal_app.as_deref())
                                {
                                    eprintln!("ssh connect {} failed: {}", alias, e);
                                }
                                None
                            } else {
                                self.prompt = Some(Prompt::SshServers {
                                    state,
                                    input,
                                    selected,
                                });
                                None
                            }
                        }
                    }
                } else {
                    None
                };
                self.show_next_pending();
                if let Some(t) = task {
                    return t;
                }
            }
            Message::PromptCancel => {
                if self.prompt.is_some() {
                    self.prompt = None;
                    self.show_next_pending();
                } else {
                    // No modal — Esc clears the active pane's filter.
                    let side = self.active;
                    let filter_was_active = {
                        let pane = self.pane_mut(side);
                        if !pane.filter.is_empty() {
                            let prior = pane.cursor_name();
                            pane.filter.clear();
                            pane.recompute_visible(prior.as_deref());
                            true
                        } else {
                            false
                        }
                    };
                    if filter_was_active {
                        // Visible row count changed (filter dropped → all
                        // entries shown again). Re-anchor scroll to the
                        // cursor — without this, the unfiltered list may
                        // still appear scrolled to the wrong position.
                        return self.ensure_active_visible();
                    }
                }
            }
            Message::FilterAppend(s) => {
                let side = self.active;
                let pane = self.pane_mut(side);
                let prior = pane.cursor_name();
                pane.filter.push_str(&s);
                pane.recompute_visible(prior.as_deref());
                // After the visible-row count changes, the existing scroll
                // position may be past the end of the new (filtered) list.
                // ensure_active_visible re-anchors scroll_y around the
                // (possibly-reset) cursor so the matching rows are on-screen.
                return self.ensure_active_visible();
            }
            Message::EntriesChunk(side, generation, chunk) => {
                // Read pending-focus state *before* the append, so we can
                // detect when this chunk is the one that resolves the focus
                // request and force a scroll in that case.
                let had_pending = self.pane(side).pending_focus.is_some();
                let pane = self.pane_mut(side);
                if pane.load_generation == generation {
                    pane.append_chunk(chunk);
                    // The chunk that resolves a focus request recenters the
                    // scroll only for a "jump to new file" focus; an in-place
                    // reload (focus_jump = false) keeps the viewport steady.
                    if had_pending
                        && self.pane(side).pending_focus.is_none()
                        && self.pane(side).focus_jump
                    {
                        return self.scroll_to_focused(side);
                    }
                    return self.ensure_active_visible();
                }
            }
            Message::EntriesDone(side, generation) => {
                let pane = self.pane_mut(side);
                if pane.load_generation == generation {
                    // All chunks have arrived — sort once now that the list is
                    // complete. This is O(n log n) total instead of the
                    // O(n² log n) that resulted from sorting in append_chunk.
                    let preserve = pane.cursor_name();
                    sort_entries(&mut pane.entries, pane.sort_by, pane.sort_dir);
                    pane.recompute_visible(preserve.as_deref());
                    pane.loading = false;
                }
            }
            Message::GitInfoLoaded(side, generation, info) => {
                let pane = self.pane_mut(side);
                if pane.load_generation == generation {
                    pane.git_info = info;
                }
            }
            Message::EditFile => {
                let pane = self.pane(self.active);
                if !pane.location.is_local() {
                    return Task::none();
                }
                if let Some(entry) = pane.entry_at(pane.selected) {
                    if entry.is_dir {
                        return Task::none();
                    }
                    let path = pane.path().join(&entry.name);
                    if let Err(e) = open_in_editor(&path) {
                        eprintln!("failed to edit {}: {}", path.display(), e);
                    }
                }
            }
            Message::QuickLook => {
                let pane = self.pane(self.active);
                if !pane.location.is_local() {
                    return Task::none();
                }
                if let Some(entry) = pane.entry_at(pane.selected) {
                    let path = pane.path().join(&entry.name);
                    if let Err(e) = quick_look(&path) {
                        eprintln!("failed to preview {}: {}", path.display(), e);
                    }
                }
            }
            Message::CopyFinished(results) => {
                self.copy_in_progress = None;
                for (src, res) in &results {
                    if let Err(e) = res {
                        eprintln!("copy {} failed: {}", src, e);
                    }
                }
                self.record_batch_errors("Copy", &results);
                return self.reload_both_panes();
            }
            Message::MoveFinished(results) => {
                self.move_in_progress = None;
                for (src, res) in &results {
                    if let Err(e) = res {
                        eprintln!("move {} failed: {}", src, e);
                    }
                }
                self.record_batch_errors("Move", &results);
                return self.reload_both_panes();
            }
            Message::CompressFinished(result) => {
                self.compress_in_progress = None;
                if let Err(e) = &result {
                    eprintln!("compress failed: {}", e);
                }
                self.last_error = result.as_ref().err().map(|e| format!("Compress failed: {}", e));
                return self.reload_both_panes();
            }
            Message::UncompressFinished(results) => {
                self.uncompress_in_progress = None;
                for (archive, res) in &results {
                    if let Err(e) = res {
                        eprintln!("uncompress {} failed: {}", archive.display(), e);
                    }
                }
                self.record_batch_errors("Extract", &results);
                return self.reload_both_panes();
            }
            Message::ExtractedToTemp(dest, result) => {
                let archive = self.extract_in_progress.take();
                match result {
                    Ok(()) => {
                        let side = self.active;
                        return self.navigate(side, Location::Local(dest));
                    }
                    Err(e) => {
                        let name = archive
                            .as_deref()
                            .map(|p| p.display().to_string())
                            .unwrap_or_else(|| dest.display().to_string());
                        eprintln!("extract {} failed: {}", name, e);
                        self.last_error = Some(format!("Extract failed: {}", e));
                    }
                }
            }
            Message::DeleteFinished(results) => {
                self.delete_in_progress = None;
                for (src, res) in &results {
                    if let Err(e) = res {
                        eprintln!("delete {} failed: {}", src, e);
                    }
                }
                self.record_batch_errors("Delete", &results);
                return self.reload_both_panes();
            }
            Message::Resized(size) => {
                self.window_size = size;
            }
            Message::WatchedDirChanged(folder) => {
                return self.refresh_local_dir(&folder);
            }
            Message::NewFilesDetected(folder, files) => {
                if files.is_empty() {
                    // Shouldn't happen — the watcher only emits non-empty
                    // batches — but guard so a stray empty event doesn't pop
                    // an empty modal.
                } else if self.prompt.is_none() {
                    self.prompt = Some(Prompt::NewFiles {
                        folder,
                        files,
                        focus: NewFilesFocus::No,
                    });
                } else {
                    self.pending_new_files.push_back((folder, files));
                }
            }
            Message::NewFilesPickSide(side) => {
                if let Some(Prompt::NewFiles { folder, files, .. }) = self.prompt.take() {
                    let task = self.navigate(side, Location::Local(folder));
                    // The watcher accumulates names in arrival order within a
                    // burst, so `.last()` is the most-recently-added file.
                    // navigate() just cleared pending_focus; set it after.
                    // focus_jump = true so the cursor recenters on the new
                    // file (a reload, by contrast, leaves it false).
                    if let Some(latest) = files.last().cloned() {
                        let pane = self.pane_mut(side);
                        pane.pending_focus = Some(latest);
                        pane.focus_jump = true;
                    }
                    self.active = side;
                    self.save_state();
                    self.show_next_pending();
                    return task;
                }
            }
            Message::OpenCommandPalette => {
                let actions = available_palette_actions(self.in_git_repo());
                self.prompt = Some(Prompt::CommandPalette {
                    input: String::new(),
                    selected: 0,
                    actions,
                    dropbox_configured: self.config.dropbox_auth().is_some(),
                });
                return text_input::focus(text_input::Id::new(PROMPT_ID));
            }
            Message::PromptMove(delta) => {
                match self.prompt.as_mut() {
                Some(Prompt::Open {
                    input,
                    recents,
                    selected,
                }) => {
                    let n = filtered_recents(recents, input).len() as i32;
                    if n > 0 {
                        *selected = (*selected as i32 + delta).rem_euclid(n) as usize;
                    }
                }
                Some(Prompt::CommandPalette {
                    input,
                    selected,
                    actions,
                    ..
                }) => {
                    let n = filtered_actions(actions, input).len() as i32;
                    if n > 0 {
                        *selected = (*selected as i32 + delta).rem_euclid(n) as usize;
                    }
                }
                Some(Prompt::Apps {
                    state,
                    input,
                    selected,
                }) => {
                    if let AppsState::Loaded(list) = state {
                        let n = filtered_apps(list, input).len() as i32;
                        if n > 0 {
                            *selected = (*selected as i32 + delta).rem_euclid(n) as usize;
                        }
                    }
                }
                Some(Prompt::GitBranches {
                    state,
                    input,
                    selected,
                    ..
                }) => {
                    if let GitBranchesState::Loaded(list) = state {
                        let n = filtered_branches(list, input).len() as i32;
                        if n > 0 {
                            *selected = (*selected as i32 + delta).rem_euclid(n) as usize;
                        }
                    }
                }
                Some(Prompt::SshServers {
                    state,
                    input,
                    selected,
                }) => {
                    if let SshServersState::Loaded(list) = state {
                        let n = filtered_servers(list, input).len() as i32;
                        if n > 0 {
                            *selected = (*selected as i32 + delta).rem_euclid(n) as usize;
                        }
                    }
                }
                _ => {}
                };
                return self.modal_scroll_to_selected();
            }
            Message::OpenRecent(path) => {
                self.prompt = None;
                self.show_next_pending();
                if path.is_dir() {
                    return self.navigate(self.active, Location::Local(path));
                }
            }
            Message::PaletteSelect(action) => {
                return self.execute_palette_action(action);
            }
            Message::DockerListLoaded(result) => {
                // Only fold the result back in if the Docker modal is still
                // up; the user may have dismissed it before docker ps
                // finished.
                if let Some(Prompt::Docker {
                    state,
                    sort_by,
                    sort_dir,
                    ..
                }) = self.prompt.as_mut()
                {
                    *state = match result {
                        Ok(mut list) => {
                            sort_containers(&mut list, *sort_by, *sort_dir);
                            DockerState::Loaded(list)
                        }
                        Err(msg) => DockerState::Error(msg),
                    };
                }
            }
            Message::DockerKill(id) => {
                return docker_kill_task(id);
            }
            Message::DockerKillFinished(id, result) => {
                if let Err(e) = &result {
                    eprintln!("docker kill {} failed: {}", id, e);
                }
                // Re-fetch the list so the killed container disappears (or
                // sticks around with a refreshed status if the kill failed).
                if let Some(Prompt::Docker { .. }) = &self.prompt {
                    return docker_ps_task();
                }
            }
            Message::DockerShell(id) => {
                if let Err(e) = docker_shell(&id, self.config.terminal_app.as_deref()) {
                    eprintln!("docker shell {} failed: {}", id, e);
                }
            }
            Message::ProcessesListLoaded(result) => {
                if let Some(Prompt::Processes {
                    state,
                    sort_by,
                    sort_dir,
                    ..
                }) = self.prompt.as_mut()
                {
                    *state = match result {
                        Ok(mut list) => {
                            sort_processes(&mut list, *sort_by, *sort_dir);
                            ProcessesState::Loaded(list)
                        }
                        Err(msg) => ProcessesState::Error(msg),
                    };
                }
            }
            Message::ProcessKill(pid) => {
                return kill_process_task(pid);
            }
            Message::ProcessKillFinished(pid, result) => {
                if let Err(e) = &result {
                    eprintln!("kill {} failed: {}", pid, e);
                }
                if let Some(Prompt::Processes { .. }) = &self.prompt {
                    return ps_task();
                }
            }
            Message::DockerToggleSort(column) => {
                if let Some(Prompt::Docker {
                    state,
                    sort_by,
                    sort_dir,
                    ..
                }) = self.prompt.as_mut()
                {
                    if *sort_by == column {
                        *sort_dir = sort_dir.toggled();
                    } else {
                        *sort_by = column;
                        *sort_dir = column.initial_dir();
                    }
                    if let DockerState::Loaded(list) = state {
                        sort_containers(list, *sort_by, *sort_dir);
                    }
                }
            }
            Message::AppsListLoaded(result) => {
                if let Some(Prompt::Apps { state, .. }) = self.prompt.as_mut() {
                    *state = match result {
                        Ok(mut list) => {
                            sort_apps(&mut list);
                            AppsState::Loaded(list)
                        }
                        Err(msg) => AppsState::Error(msg),
                    };
                }
            }
            Message::LaunchApp(path) => {
                self.prompt = None;
                self.show_next_pending();
                if let Err(e) = launch_app(&path) {
                    eprintln!("launch {} failed: {}", path.display(), e);
                }
            }
            Message::GitBranchesLoaded(result) => {
                if let Some(Prompt::GitBranches { state, .. }) = self.prompt.as_mut() {
                    // git for-each-ref already returns committerdate-sorted
                    // rows, so we hand them through unchanged.
                    *state = match result {
                        Ok(list) => GitBranchesState::Loaded(list),
                        Err(msg) => GitBranchesState::Error(msg),
                    };
                }
            }
            Message::GitCheckout(branch) => {
                if let Some(Prompt::GitBranches { repo_path, .. }) = &self.prompt {
                    let path = repo_path.clone();
                    return git_checkout_task(path, branch);
                }
            }
            Message::SshServersLoaded(result) => {
                if let Some(Prompt::SshServers { state, .. }) = self.prompt.as_mut() {
                    *state = match result {
                        Ok(list) => SshServersState::Loaded(list),
                        Err(msg) => SshServersState::Error(msg),
                    };
                }
            }
            Message::SshConnect(alias) => {
                // Close the modal first — the terminal launches in a separate
                // window, so once it's spawned the user is interacting with
                // ssh, not with us.
                self.prompt = None;
                self.show_next_pending();
                match ssh_connect(&alias, self.config.terminal_app.as_deref()) {
                    Ok(()) => self.last_error = None,
                    Err(e) => {
                        // Surface it in the status bar rather than only stderr —
                        // most often "Not authorized to send Apple events" until
                        // the app is granted Automation access to the terminal.
                        let msg = format!("SSH connect to {} failed: {}", alias, e);
                        eprintln!("{}", msg);
                        self.last_error = Some(msg);
                    }
                }
            }
            Message::SshOpenInPane(alias) => {
                // Close the modal, then point the active pane at the host's
                // home directory. `~` gets expanded by the remote login
                // shell during the first `ls`, so we don't need a separate
                // `pwd` round-trip up-front.
                self.prompt = None;
                self.show_next_pending();
                let side = self.active;
                return self.navigate(
                    side,
                    Location::Remote {
                        backend: BackendId::new(alias),
                        path: PathBuf::from("~"),
                    },
                );
            }
            Message::GitCheckoutFinished(branch, result) => {
                match result {
                    Ok(()) => {
                        // Switch to the new branch — close the modal and refresh
                        // both panes so file listings + git_info reflect HEAD.
                        self.prompt = None;
                        self.show_next_pending();
                        return self.reload_both_panes();
                    }
                    Err(e) => {
                        eprintln!("git checkout {} failed: {}", branch, e);
                        // Surface the error in the modal so the user knows it
                        // didn't take effect (dirty tree, missing branch, …).
                        if let Some(Prompt::GitBranches { state, .. }) = self.prompt.as_mut() {
                            *state = GitBranchesState::Error(e);
                        }
                    }
                }
            }
            Message::ExitApp => {
                return window::get_oldest().and_then(window::close);
            }
            Message::ProcessToggleSort(column) => {
                if let Some(Prompt::Processes {
                    state,
                    sort_by,
                    sort_dir,
                    ..
                }) = self.prompt.as_mut()
                {
                    if *sort_by == column {
                        *sort_dir = sort_dir.toggled();
                    } else {
                        *sort_by = column;
                        *sort_dir = column.initial_dir();
                    }
                    if let ProcessesState::Loaded(list) = state {
                        sort_processes(list, *sort_by, *sort_dir);
                    }
                }
            }
            Message::NoOp => {}
        }
        Task::none()
    }

    /// Dispatch a command-palette action. Shared between direct clicks
    /// (`PaletteSelect`) and Enter-on-highlighted (`PromptSubmit`).
    fn execute_palette_action(&mut self, action: PaletteAction) -> Task<Message> {
        self.prompt = None;
        match action {
            PaletteAction::Copy => {
                let other = self.active.other();
                let dest = self.pane(other).location.to_string();
                self.prompt = Some(Prompt::Copy { input: dest });
                text_input::focus(text_input::Id::new(PROMPT_ID))
            }
            PaletteAction::Move => {
                let other = self.active.other();
                let dest = self.pane(other).location.to_string();
                self.prompt = Some(Prompt::Move { input: dest });
                text_input::focus(text_input::Id::new(PROMPT_ID))
            }
            PaletteAction::Delete => {
                let paths = self.pane(self.active).marked_locations();
                if !paths.is_empty() {
                    self.prompt = Some(Prompt::Delete {
                        paths,
                        focus: DeleteFocus::Cancel,
                    });
                }
                Task::none()
            }
            PaletteAction::Compress => {
                if !self.both_panes_local() {
                    return Task::none();
                }
                let marked = self.pane(self.active).marked_paths();
                if marked.is_empty() {
                    return Task::none();
                }
                let other = self.active.other();
                let dest_dir = self.pane(other).path().to_path_buf();
                let default_path = dest_dir.join(default_zip_filename(&marked));
                self.prompt = Some(Prompt::Compress {
                    input: default_path.display().to_string(),
                });
                text_input::focus(text_input::Id::new(PROMPT_ID))
            }
            PaletteAction::Uncompress => {
                if !self.both_panes_local() {
                    return Task::none();
                }
                let marked = self.pane(self.active).marked_paths();
                if marked.is_empty() {
                    return Task::none();
                }
                let other = self.active.other();
                let dest = self.pane(other).path().display().to_string();
                self.prompt = Some(Prompt::Uncompress { input: dest });
                text_input::focus(text_input::Id::new(PROMPT_ID))
            }
            PaletteAction::DockerContainers => {
                self.prompt = Some(Prompt::Docker {
                    state: DockerState::Loading,
                    input: String::new(),
                    sort_by: DockerSortBy::Name,
                    sort_dir: SortDir::Asc,
                });
                Task::batch([
                    docker_ps_task(),
                    text_input::focus(text_input::Id::new(PROMPT_ID)),
                ])
            }
            PaletteAction::Processes => {
                self.prompt = Some(Prompt::Processes {
                    state: ProcessesState::Loading,
                    input: String::new(),
                    sort_by: ProcessSortBy::Cpu,
                    sort_dir: SortDir::Desc,
                });
                Task::batch([
                    ps_task(),
                    text_input::focus(text_input::Id::new(PROMPT_ID)),
                ])
            }
            PaletteAction::LaunchApplication => {
                self.reset_modal_scroll();
                self.prompt = Some(Prompt::Apps {
                    state: AppsState::Loading,
                    input: String::new(),
                    selected: 0,
                });
                Task::batch([
                    apps_task(),
                    text_input::focus(text_input::Id::new(PROMPT_ID)),
                ])
            }
            PaletteAction::GitBranch => {
                if !self.pane(self.active).location.is_local() {
                    return Task::none();
                }
                let repo_path = self.pane(self.active).path().to_path_buf();
                self.reset_modal_scroll();
                self.prompt = Some(Prompt::GitBranches {
                    state: GitBranchesState::Loading,
                    input: String::new(),
                    selected: 0,
                    repo_path: repo_path.clone(),
                });
                Task::batch([
                    git_branches_task(repo_path),
                    text_input::focus(text_input::Id::new(PROMPT_ID)),
                ])
            }
            PaletteAction::KeyboardShortcuts => {
                self.prompt = Some(Prompt::KeyboardShortcuts);
                Task::none()
            }
            PaletteAction::SshConnect => {
                self.reset_modal_scroll();
                self.prompt = Some(Prompt::SshServers {
                    state: SshServersState::Loading,
                    input: String::new(),
                    selected: 0,
                });
                Task::batch([
                    ssh_servers_task(),
                    text_input::focus(text_input::Id::new(PROMPT_ID)),
                ])
            }
            PaletteAction::OpenDropbox => {
                // Point the active pane at the Dropbox account root. The
                // first `list_folder` mints an access token from the
                // configured refresh token; if that's missing the action
                // wouldn't have been offered.
                let side = self.active;
                return self.navigate(
                    side,
                    Location::Remote {
                        backend: BackendId::new(BackendId::DROPBOX),
                        path: PathBuf::from("/"),
                    },
                );
            }
            PaletteAction::OpenClaudeCode => {
                // Fire-and-forget: spawn a terminal with `claude` running in
                // the active pane's directory. No modal — the action just
                // launches and closes the palette.
                if !self.pane(self.active).location.is_local() {
                    return Task::none();
                }
                let path = self.pane(self.active).path().to_path_buf();
                if let Err(e) = open_claude_code(&path, self.config.terminal_app.as_deref()) {
                    eprintln!("open Claude Code in {} failed: {}", path.display(), e);
                }
                Task::none()
            }
            PaletteAction::Exit => window::get_oldest().and_then(window::close),
        }
    }

    /// If the currently-displayed modal has just closed and we have queued
    /// new-file detections waiting, surface the next one.
    fn show_next_pending(&mut self) {
        if self.prompt.is_some() {
            return;
        }
        if let Some((folder, files)) = self.pending_new_files.pop_front() {
            self.prompt = Some(Prompt::NewFiles {
                folder,
                files,
                focus: NewFilesFocus::No,
            });
        }
    }

    /// Record (or clear) `last_error` from a batch of per-source results.
    /// `verb` is the capitalised action ("Copy", "Move", "Delete",
    /// "Extract"). Delegates to the pure [`batch_error_message`].
    fn record_batch_errors<T>(&mut self, verb: &str, results: &[(T, Result<(), String>)]) {
        let errors = results.iter().filter_map(|(_, r)| r.as_ref().err());
        self.last_error = batch_error_message(verb, errors);
    }

    /// Returns a transient status string when something async is happening.
    /// Priority is copy > delete > load (copy/delete usually start *after*
    /// the panes have loaded, so this ordering surfaces the user-initiated
    /// action over background loading noise).
    fn status_text(&self) -> Option<String> {
        if let Some((count, dest)) = &self.copy_in_progress {
            let noun = if *count == 1 { "file" } else { "files" };
            return Some(format!("Copying {} {} to {}…", count, noun, dest));
        }
        if let Some((count, dest)) = &self.move_in_progress {
            let noun = if *count == 1 { "file" } else { "files" };
            return Some(format!("Moving {} {} to {}…", count, noun, dest));
        }
        if let Some((count, output)) = &self.compress_in_progress {
            let noun = if *count == 1 { "file" } else { "files" };
            return Some(format!(
                "Compressing {} {} → {}…",
                count,
                noun,
                output.display()
            ));
        }
        if let Some((count, dest)) = &self.uncompress_in_progress {
            let noun = if *count == 1 { "archive" } else { "archives" };
            return Some(format!(
                "Extracting {} {} to {}…",
                count,
                noun,
                dest.display()
            ));
        }
        if let Some(archive) = &self.extract_in_progress {
            let name = archive
                .file_name()
                .map(|n| n.to_string_lossy().into_owned())
                .unwrap_or_else(|| archive.display().to_string());
            return Some(format!("Extracting {} to /tmp…", name));
        }
        if let Some(count) = self.delete_in_progress {
            let noun = if count == 1 { "file" } else { "files" };
            return Some(format!("Deleting {} {}…", count, noun));
        }
        if self.left.loading || self.right.loading {
            let loading_side = if self.left.loading {
                Side::Left
            } else {
                Side::Right
            };
            let p = self.pane(loading_side);
            return Some(format!("Loading {}…", p.location));
        }
        None
    }

    fn view(&self) -> Element<'_, Message> {
        let colors = row_colors_from(&self.config);
        let name_max = name_max_chars(self.window_size.width, &self.config);
        let panes = row![
            view_pane(
                Side::Left,
                &self.left,
                self.active == Side::Left,
                name_max,
                &self.config,
                colors,
                self.window_size.height,
            ),
            view_pane(
                Side::Right,
                &self.right,
                self.active == Side::Right,
                name_max,
                &self.config,
                colors,
                self.window_size.height,
            ),
        ]
        .spacing(8)
        .height(Length::Fill);

        // Black background + dim text — the quietest band we can give a row
        // that still needs to be readable. Same look for "Ready" and for any
        // in-progress task message.
        // An error from the last finished op takes precedence over the
        // in-progress / "Ready" status and is shown in red until the next
        // copy/move/delete/compress/extract starts.
        let (status_msg, is_error) = match &self.last_error {
            Some(err) => (err.clone(), true),
            None => (self.status_text().unwrap_or_else(|| "Ready".to_string()), false),
        };
        let status_bar: Element<'_, Message> = container(text(status_msg).size(11))
            .padding(Padding::from([4, 8]))
            .width(Length::Fill)
            .style(move |theme: &Theme| container::Style {
                background: Some(Color::BLACK.into()),
                text_color: Some(if is_error {
                    Color::from_rgb(1.0, 0.45, 0.45)
                } else {
                    dim(theme.extended_palette().background.base.text)
                }),
                ..Default::default()
            })
            .into();

        let base: Element<'_, Message> = container(column![panes, status_bar].spacing(6))
            .padding(8)
            .width(Length::Fill)
            .height(Length::Fill)
            .into();

        if let Some(prompt) = &self.prompt {
            stack![base, view_modal(prompt)].into()
        } else {
            base
        }
    }

    fn subscription(&self) -> Subscription<Message> {
        let key_press = keyboard::on_key_press(|key, mods: Modifiers| {
            match key {
                Key::Character(ref c)
                    if mods.command() && mods.shift() && c.eq_ignore_ascii_case("p") =>
                {
                    Some(Message::OpenCommandPalette)
                }
                Key::Character(ref c) if mods.command() && c.eq_ignore_ascii_case("p") => {
                    Some(Message::OpenPrompt)
                }
                Key::Character(ref c) if mods.command() && c.as_str() == "," => {
                    Some(Message::OpenSettingsFile)
                }
                // Esc is handled by the dedicated `esc_listener`
                // subscription below — text_input captures Esc to clear its
                // own focus, so routing it through `on_key_press` (which
                // only fires on Ignored events) makes the user hit Esc
                // twice. `event::listen_with` sees the press regardless
                // of widget capture.
                Key::Named(Named::ArrowUp) => Some(Message::MoveSelection(-1, mods.shift())),
                Key::Named(Named::ArrowDown) => Some(Message::MoveSelection(1, mods.shift())),
                Key::Named(Named::PageUp) => Some(Message::PageMove(-1, mods.shift())),
                Key::Named(Named::PageDown) => Some(Message::PageMove(1, mods.shift())),
                // ←/→ are only meaningful inside the Delete modal; in main
                // view the SwitchPromptFocus handler is a no-op.
                Key::Named(Named::ArrowLeft) | Key::Named(Named::ArrowRight) => {
                    Some(Message::SwitchPromptFocus)
                }
                Key::Named(Named::Enter) => Some(Message::ActivateSelection),
                Key::Named(Named::Tab) => Some(Message::SwitchSide),
                Key::Named(Named::Backspace) => Some(Message::GoUpActive),
                Key::Named(Named::Delete) => Some(Message::OpenDeletePrompt),
                Key::Named(Named::F4) => Some(Message::EditFile),
                Key::Named(Named::Space) => Some(Message::QuickLook),
                Key::Named(Named::F5) => Some(Message::OpenCopyPrompt),
                Key::Named(Named::F6) => Some(Message::OpenMovePrompt),
                Key::Named(Named::F10) => Some(Message::ExitApp),
                // Plain character keys (no Ctrl/Cmd/Alt) feed the type-to-filter.
                // The earlier Cmd+P / Cmd+, guards have already matched before
                // we get here, so unmodified characters fall through to this.
                Key::Character(c) if !mods.command() && !mods.control() && !mods.alt() => {
                    Some(Message::FilterAppend(c.to_string()))
                }
                _ => None,
            }
        });

        // Shift state — tracked via the raw `ModifiersChanged` event so it
        // fires regardless of widget capture. The earlier `on_key_press` /
        // `on_key_release` based approach only fired on `Status::Ignored`,
        // which meant a released-after-click shift could be swallowed by
        // the focused button and leave `shift_held` stuck `true` — causing
        // the next plain click to extend the selection.
        let mods_listener =
            iced::event::listen_with(|event, _status, _window| match event {
                iced::Event::Keyboard(keyboard::Event::ModifiersChanged(mods)) => {
                    Some(Message::ShiftChanged(mods.shift()))
                }
                _ => None,
            });

        // Esc — captured at the raw-event level (status is intentionally
        // ignored) so it fires even when a `text_input` has focus and
        // would otherwise swallow the first press to clear its own focus.
        // `PromptCancel` is idempotent: closes the current modal if any,
        // else clears the active pane's filter, else no-op.
        let esc_listener =
            iced::event::listen_with(|event, _status, _window| match event {
                iced::Event::Keyboard(keyboard::Event::KeyPressed {
                    key: Key::Named(Named::Escape),
                    ..
                }) => Some(Message::PromptCancel),
                _ => None,
            });

        let resizes = window::resize_events().map(|(_, size)| Message::Resized(size));

        let settings_poll = time::every(Duration::from_secs(1)).map(|_| Message::CheckSettings);

        let mut subs = vec![key_press, mods_listener, esc_listener, resizes, settings_poll];

        // Watch folders are read once at startup (same lifecycle as window
        // size). Filter out paths that don't exist so notify::watch() doesn't
        // log a misleading error.
        let watched: Vec<PathBuf> = self
            .config
            .watch_folders
            .iter()
            .map(|s| PathBuf::from(expand_tilde(s)))
            .filter(|p| p.is_dir())
            .collect();
        if !watched.is_empty() {
            subs.push(file_watch_subscription(watched));
        }

        // Watch the panes' own open directories and auto-refresh on change.
        // Unlike the configured watch_folders above, this set changes as the
        // user navigates, so `pane_watch_subscription` keys its id off the
        // folder list — iced restarts the watcher when the panes move.
        let mut pane_dirs: Vec<PathBuf> = [&self.left, &self.right]
            .into_iter()
            .filter_map(|p| match &p.location {
                Location::Local(path) => Some(path.clone()),
                Location::Remote { .. } => None,
            })
            .filter(|p| p.is_dir())
            .collect();
        pane_dirs.sort();
        pane_dirs.dedup();
        if !pane_dirs.is_empty() {
            subs.push(pane_watch_subscription(pane_dirs));
        }

        Subscription::batch(subs)
    }
}

/// Stat `pane.path()` for the Claude context markers (`CLAUDE.md` /
/// `.claude/`) and update the pane's cached booleans. Called on every
/// navigate / reload — same lifecycle as `git_info`. Skipped for remote
/// panes: stat'ing the *local* filesystem at the remote path would be
/// meaningless, and probing the marker over ssh isn't worth the round-
/// trip for Phase 2 MVP.
fn refresh_claude_marker(pane: &mut Pane) {
    if !pane.location.is_local() {
        pane.has_claude_md = false;
        pane.has_claude_dir = false;
        return;
    }
    pane.has_claude_md = pane.path().join("CLAUDE.md").is_file();
    pane.has_claude_dir = pane.path().join(".claude").is_dir();
}

/// Parse the trimmed text of a Copy/Move prompt input into a
/// [`Location`]. Wraps `Location::from_str` (which is infallible) with
/// the tilde-expansion the prompts have always done for local paths.
fn parse_dest_location(input: &str) -> Location {
    let trimmed = input.trim();
    let parsed: Location = trimmed.parse().expect("Location::from_str is infallible");
    match parsed {
        // Tilde-expand local paths so `~/Downloads` resolves like it
        // used to before the Location refactor.
        Location::Local(p) => Location::Local(PathBuf::from(expand_tilde(&p.to_string_lossy()))),
        other => other,
    }
}

/// Validate that a Copy/Move destination is plausible before kicking
/// off the task. Local paths must exist as a directory (matches the
/// pre-Phase-3 behaviour); remote paths are trusted — sftp will
/// surface a clearer error than we can guess up-front.
fn dest_exists(loc: &Location) -> bool {
    match loc {
        Location::Local(p) => p.is_dir(),
        Location::Remote { .. } => true,
    }
}

/// True if the path's extension is `zip` (case-insensitive). Used to gate
/// Enter-on-archive extraction.
fn is_zip(path: &std::path::Path) -> bool {
    path.extension()
        .and_then(|e| e.to_str())
        .map(|s| s.eq_ignore_ascii_case("zip"))
        .unwrap_or(false)
}

/// Build a status-bar error string for a finished batch operation, or
/// `None` when nothing failed. `verb` is the capitalised action
/// ("Copy", "Move", …). Surfaces the first failure verbatim, with a
/// `(N errors)` count when more than one source failed.
fn batch_error_message<'a>(
    verb: &str,
    errors: impl IntoIterator<Item = &'a String>,
) -> Option<String> {
    let errors: Vec<&String> = errors.into_iter().collect();
    match errors.as_slice() {
        [] => None,
        [one] => Some(format!("{} failed: {}", verb, one)),
        many => Some(format!("{} failed ({} errors): {}", verb, many.len(), many[0])),
    }
}

#[cfg(test)]
mod tests {
    use super::{batch_error_message, is_zip, APP_ICON};
    use std::path::Path;

    #[test]
    fn app_icon_is_valid_png_and_decodes() {
        // Catches a missing/corrupt assets/icon.png and confirms the iced
        // `image` feature can turn it into a window icon.
        assert_eq!(&APP_ICON[..8], b"\x89PNG\r\n\x1a\n");
        assert!(iced::window::icon::from_file_data(APP_ICON, None).is_ok());
    }

    #[test]
    fn batch_error_message_none_when_all_ok() {
        assert_eq!(batch_error_message("Copy", std::iter::empty()), None);
    }

    #[test]
    fn batch_error_message_single_failure_is_verbatim() {
        let errs = vec!["no such file".to_string()];
        assert_eq!(
            batch_error_message("Copy", errs.iter()),
            Some("Copy failed: no such file".to_string()),
        );
    }

    #[test]
    fn batch_error_message_multiple_failures_shows_count_and_first() {
        let errs = vec!["denied".to_string(), "timeout".to_string()];
        assert_eq!(
            batch_error_message("Delete", errs.iter()),
            Some("Delete failed (2 errors): denied".to_string()),
        );
    }

    #[test]
    fn is_zip_matches_lowercase() {
        assert!(is_zip(Path::new("archive.zip")));
    }

    #[test]
    fn is_zip_matches_uppercase() {
        assert!(is_zip(Path::new("ARCHIVE.ZIP")));
    }

    #[test]
    fn is_zip_rejects_tar_gz() {
        assert!(!is_zip(Path::new("archive.tar.gz")));
    }

    #[test]
    fn is_zip_rejects_no_extension() {
        assert!(!is_zip(Path::new("README")));
    }
}
